//-----------------------------------------------------------
//
//  File IIOAccel.cpp generated by RTembedded
//  Created at: Mon Jun 15 16:09:31 2015
//  This file will not be regenerated unless deleted and can be modified as required
//
//-----------------------------------------------------------

#include "IIOAccel.h"
#include <qdebug.h>
#include <unistd.h>
#include <signal.h>

volatile bool IIOAccel::sigIntReceived = false;

IIOAccel::IIOAccel(QObject *parent) : MainClass(parent)
{
}

void IIOAccel::setup()
{
    registerSigHandler();
    m_lastTimestamp = 0;
}

void IIOAccel::loop()
{
    RTeModule *module;
    RTeSensorAccelData accelData;

    if (newAccelSample_getLastOnly(module, accelData)) {
        qDebug() << qPrintable(accelData.m_accel.display("Accel:")) << ", " << accelData.m_timestamp - m_lastTimestamp << "uS";
        m_lastTimestamp = accelData.m_timestamp;
    }

    if (IIOAccel::sigIntReceived)
        quit();
}

void IIOAccel::registerSigHandler()
{
    struct sigaction sia;
    bzero(&sia, sizeof(sia));
    sia.sa_handler = IIOAccel::sigHandler;
    if (sigaction(SIGINT, &sia, NULL) < 0) perror("sigaction(SIGINT)");
}

void IIOAccel::sigHandler(int)
{
    IIOAccel::sigIntReceived = true;
}
