#-----------------------------------------------------------
#
#  File IIOAccel.pri generated by RTembedded
#  Created at: Mon Jun 15 16:09:31 2015 
#  This file will not be regenerated unless deleted and can be modified as required
#
#-----------------------------------------------------------

HEADERS += MainClass.h \ 
    IIOAccel.h \ 

SOURCES += MainClass.cpp \ 
    main.cpp \ 
    IIOAccel.cpp \ 
