//-----------------------------------------------------------
//
//  File main.cpp generated by RTembedded
//  Created at: Mon Jun 15 16:34:31 2015 
//  *** Note - this file will be overwritten if the project is regenerated ***
//
//-----------------------------------------------------------

#include <qcoreapplication.h>

#include "IIOAccel.h"

int main(int argc, char *argv[])
{
    QCoreApplication a(argc, argv);
    IIOAccel mc;

    QObject::connect(&mc, SIGNAL(finished()), &a, SLOT(quit()));
    QObject::connect(&a, SIGNAL(aboutToQuit()), &mc, SLOT(aboutToQuit()));

    QMetaObject::invokeMethod(&mc, "run", Qt::QueuedConnection);
    return a.exec();
}
