//-----------------------------------------------------------
//
//  File MainClass.h generated by RTembedded
//  Created at: Tue Jun 16 10:26:57 2015 
//  *** Note - this file will be overwritten if the project is regenerated ***
//
//-----------------------------------------------------------

#ifndef _MAINCLASS_H
#define _MAINCLASS_H

#include <qobject.h>
#include <qmutex.h>
#include <qqueue.h>
#include "RTeModule.h"

#include "RTeIIOAccel.h"

class newAccelSampleSlotClass
{
public:
    RTeModule *m_module;
    RTeSensorAccelData m_parameter;
};


class MainClass : public QObject
{
    Q_OBJECT

public:
    MainClass(QObject *parent = 0);
    void quit();

public slots:
    void run();
    void aboutToQuit();
    bool newAccelSample_get(RTeModule* &, RTeSensorAccelData &);
    bool newAccelSample_getLastOnly(RTeModule* &, RTeSensorAccelData &);
    void newAccelSample_put(RTeModule *, RTeSensorAccelData *);

signals:
    void finished();

protected:
    virtual void setup() {}
    virtual void loop() {}

    RTeIIOAccel *m_accel;

private:
   QQueue<newAccelSampleSlotClass> m_newAccelSampleSlotQueue;
   QMutex m_newAccelSampleSlotQueueMutex;

    bool m_running;
};


#endif // _MAINCLASS_H
